-- =========================================================================
-- 開発依頼 / エラー進捗報告 / 進捗管理 (Salon One 開発対応表のシステム化)
--   - profiles.role:       アカウント種別を3種に拡張
--                          (admin=全体管理者 / billing=請求管理のみ / dev=開発進捗のみ)
--                          旧ロール owner/staff は後方互換のため残す
--   - dev_issues:          開発依頼(不具合・要望)。スプレッドシートの1行に相当
--   - dev_issue_approvals: プロダクト管理者の実行判定(2名承諾で「実行」)
--   - notifications:       アプリ内通知(対応完了・新規依頼・追加ヒアリング等)
-- =========================================================================

-- アカウント種別の拡張 ------------------------------------------------------
alter table profiles drop constraint if exists profiles_role_check;
alter table profiles add constraint profiles_role_check
  check (role in ('owner','staff','admin','billing','dev'));

-- 開発依頼 ------------------------------------------------------------------
create table if not exists dev_issues (
  id             uuid primary key default gen_random_uuid(),
  issue_number   int generated by default as identity,        -- 表示用の連番 (#12)
  title          text not null,                               -- 課題名
  detail         text not null default '',                    -- 詳細
  category       text not null default 'bug'
                 check (category in ('bug','request')),       -- 分類: 不具合/要望
  priority       text not null default 'medium'
                 check (priority in ('high','medium','low')), -- 優先度: 高/中/低
  status         text not null default 'open'
                 check (status in ('open','in_progress','hearing','done')),
  execution      text not null default 'undecided'
                 check (execution in ('undecided','approved','rejected')),
  requester_id   uuid references profiles(id) on delete set null, -- 依頼者
  requester_name text not null default '',                    -- 依頼者名(退職後も表示)
  scheduled_date date,                                        -- 対応完了予定日
  completed_date date,                                        -- 対応完了日
  dev_note       text not null default '',                    -- 開発対応内容
  created_at     timestamptz not null default now(),          -- 記載日
  updated_at     timestamptz not null default now()
);

-- 実行判定(プロダクト管理者ごとに1件) --------------------------------------
create table if not exists dev_issue_approvals (
  id            uuid primary key default gen_random_uuid(),
  issue_id      uuid not null references dev_issues(id) on delete cascade,
  approver_id   uuid not null,
  approver_name text not null default '',
  decision      text not null check (decision in ('approve','reject')),
  created_at    timestamptz not null default now(),
  unique (issue_id, approver_id)
);

-- アプリ内通知 --------------------------------------------------------------
create table if not exists notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null,                                   -- 受信者(profiles.id)
  type       text not null
             check (type in ('issue_created','issue_done','issue_hearing','issue_execution')),
  message    text not null,
  issue_id   uuid references dev_issues(id) on delete cascade,
  read       boolean not null default false,
  created_at timestamptz not null default now()
);

-- インデックス --------------------------------------------------------------
create index if not exists idx_dev_issues_status on dev_issues(status);
create index if not exists idx_dev_issues_created on dev_issues(created_at desc);
create index if not exists idx_dev_issue_approvals_issue on dev_issue_approvals(issue_id);
create index if not exists idx_notifications_user on notifications(user_id, read, created_at desc);

-- updated_at 自動更新 --------------------------------------------------------
create or replace function public.touch_dev_issue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists dev_issues_touch_updated on dev_issues;
create trigger dev_issues_touch_updated
  before update on dev_issues
  for each row execute function public.touch_dev_issue_updated_at();

-- RLS ------------------------------------------------------------------------
alter table dev_issues          enable row level security;
alter table dev_issue_approvals enable row level security;
alter table notifications      enable row level security;

-- 開発依頼・実行判定: 認証済みユーザーは読み書き可能(細かい権限はアプリ層で制御。
-- 通常の書き込みはサービスロール経由 = getServiceRepository を使用)
drop policy if exists dev_issues_authenticated_all on dev_issues;
create policy dev_issues_authenticated_all on dev_issues
  for all to authenticated using (true) with check (true);

drop policy if exists dev_issue_approvals_authenticated_all on dev_issue_approvals;
create policy dev_issue_approvals_authenticated_all on dev_issue_approvals
  for all to authenticated using (true) with check (true);

-- 通知: 本人の通知のみ参照・既読化できる(作成はサービスロールが行う)
drop policy if exists notifications_select_own on notifications;
create policy notifications_select_own on notifications
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists notifications_update_own on notifications;
create policy notifications_update_own on notifications
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
